# ============================================================
#  FUNDING.yml — tsforge
#  Author  : Jack
#  GitHub  : https://github.com/setuju
#  Website : https://saturumah.net
# ============================================================

github: setuju
custom:
  - https://saturumah.net